-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TICKET_REPLY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REPORT_STATUS';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TICKET_RESOLVED';
