-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'USER';
ALTER TABLE "User" ALTER COLUMN "status" SET DEFAULT 'PENDING_VERIFICATION';
ALTER TABLE "User" ALTER COLUMN "rating" SET DEFAULT 0;
ALTER TABLE "User" ALTER COLUMN "ratingCount" SET DEFAULT 0;
ALTER TABLE "User" ALTER COLUMN "twoFactorEnabled" SET DEFAULT false;
ALTER TABLE "User" ALTER COLUMN "emailVerified" SET DEFAULT false;
ALTER TABLE "User" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");
