-- TicketStatus.AWAITING_VERDICT + NotificationType.TICKET_VERDICT_REQUESTED
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'AWAITING_VERDICT';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TICKET_VERDICT_REQUESTED';
